### ISSUE TITLE
The "range_end" IP is not available

### ISSUE THREAD

**Issue by clivez** [openshift/whereabouts-cni#10]
> range_end : Last IP to use when allocating from the range. Optional, if unset the last ip within the range is determined.

But actually this last IP is not available, for example if I use the configuration
```
        "range": "192.168.2.0/24",
	"range_start": "192.168.2.10",
	"range_end": "192.168.2.15",
```
only 192.168.2.10-192.168.2.14 can be allocated, 192.168.2.15 is not available.

**Comment by bysnupy** [comment]
This issue has been fixed here: https://github.com/openshift/whereabouts-cni/pull/12
