### ISSUE TITLE
IPV6 range syntax and Support Query

### ISSUE THREAD

**Issue by pradeepcp1** [openshift/whereabouts-cni#6]
Sorry, it's not issue but query,

Does whereabout support range_startand range_end for IPV6 too?
Also is the exclusion range is applicable/useable for IPV6 aswell?
Example:
"range": "2001::0/116",
"exclude": [
"2001::0/122",
"2001::9999/128"
],

Also is below range syntax valid for IPV6?
range: "2001::1-2001::100 /116"

**Comment by dionysius** [comment]
Can't answer your query, but I noticed `2001::1-2001::100` can't be valid, as there's only one '::' in IPv6 allowed
